name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Disable code signing
        run: |
          echo "CSC_IDENTITY_AUTO_DISCOVERY=false" >> $GITHUB_ENV

      - name: Install dependencies
        run: PUPPETEER_SKIP_DOWNLOAD=true npm install

      - name: Build macOS App
        run: npm run dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kinx-auto-macos
          path: dist/*
